import type { IconType } from "react-icons";
import {
  SiPython,
  SiNextdotjs,
  SiHtml5,
  SiTiktok,
  SiStoryblok,
  SiDiscord,
  SiDocker,
  SiTypescript,
  SiJavascript,
  SiReact,
  SiTailwindcss,
  SiCss3,
  SiVercel,
  SiGithub,
  SiGit,
  SiFigma,
  SiSlack,
  SiJira,
  SiNotion,
  SiHubspot,
  SiSalesforce,
  SiGoogleanalytics,
  SiGoogleads,
  SiMeta,
  SiFacebook,
  SiLinkedin,
  SiFirebase,
  SiSupabase,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiStripe,
  SiShopify,
  SiWordpress,
  SiWebflow,
  SiAirtable,
  SiZapier,
  SiResend,
  SiContentful,
  SiPrisma,
  SiNodedotjs,
  SiDeno,
  SiBun,
  SiMailchimp,
  SiSendgrid,
  SiGooglesheets,
  SiTableau,
  SiLooker,
  SiAsana,
  SiClickup,
  SiTrello,
  SiIntercom,
  SiZendesk,
  SiSemrush,
  SiGooglesearchconsole,
  SiCanva,
  SiAmazonwebservices,
  SiCloudflare,
  SiRailway,
  SiSteam,
  SiPandas,
  SiGooglebigquery,
  SiRender,
  SiOculus,
  SiUnity,
  SiMdx,
} from "react-icons/si";
import {
  TbBrandMonday,
  TbBadge4K,
  TbDeviceMobile,
  TbBrandDiscordFilled,
  TbBrowser,
} from "react-icons/tb";
import {
  HiOutlineChartBar,
  HiOutlineLightBulb,
  HiOutlineRocketLaunch,
  HiOutlineMegaphone,
  HiOutlineUserGroup,
  HiOutlineCog6Tooth,
  HiOutlineBolt,
  HiOutlineChartPie,
  HiOutlineHandRaised,
  HiOutlineCubeTransparent,
  HiOutlineCursorArrowRays,
  HiOutlinePresentationChartLine,
  HiOutlineEnvelope,
  HiOutlineWrenchScrewdriver,
  HiOutlineMapPin,
  HiOutlineArrowTrendingUp,
  HiOutlineCodeBracket,
  HiOutlineServerStack,
  HiOutlineCommandLine,
} from "react-icons/hi2";

const iconMap: Record<string, IconType> = {
  // Tech stack
  "unity engine": SiUnity,
  "oculus mobile sdk": SiOculus,
  "render": SiRender,
  "google bigquery": SiGooglebigquery,
  "pandas": SiPandas,
  "python": SiPython,
  "next.js": SiNextdotjs,
  "nextjs": SiNextdotjs,
  "html": SiHtml5,
  "html5": SiHtml5,
  "css": SiCss3,
  "css3": SiCss3,
  "javascript": SiJavascript,
  "js": SiJavascript,
  "typescript": SiTypescript,
  "ts": SiTypescript,
  "react": SiReact,
  "react.js": SiReact,
  "tailwind": SiTailwindcss,
  "tailwindcss": SiTailwindcss,
  "tailwind css": SiTailwindcss,
  "node.js": SiNodedotjs,
  "nodejs": SiNodedotjs,
  "node": SiNodedotjs,
  "deno": SiDeno,
  "bun": SiBun,
  "docker": SiDocker,
  "git": SiGit,
  "github": SiGithub,
  "vercel": SiVercel,
  "prisma": SiPrisma,
  "firebase": SiFirebase,
  "supabase": SiSupabase,
  "postgresql": SiPostgresql,
  "postgres": SiPostgresql,
  "postgree sql": SiPostgresql,
  "postgres sql": SiPostgresql,
  "mongodb": SiMongodb,
  "redis": SiRedis,
  "aws": SiAmazonwebservices,
  "amazon web services": SiAmazonwebservices,
  "stripe": SiStripe,
  "discord.js": TbBrandDiscordFilled,
  "mdx": SiMdx,
  "playwright": TbBrowser,

  // CMS & website builders
  "storyblok": SiStoryblok,
  "contentful": SiContentful,
  "wordpress": SiWordpress,
  "webflow": SiWebflow,
  "shopify": SiShopify,

  // APIs & platforms
  "discord": SiDiscord,
  "discord api": SiDiscord,
  "tiktok": SiTiktok,
  "tiktok business api": SiTiktok,
  "meta": SiMeta,
  "meta ads": SiMeta,
  "facebook": SiFacebook,
  "facebook ads": SiFacebook,
  "linkedin": SiLinkedin,
  "resend": SiResend,
  "steam api": SiSteam,
  "steam": SiSteam,
  "cloudflare": SiCloudflare,
  "railway": SiRailway,
  "railways": SiRailway,

  // Design & productivity
  "figma": SiFigma,
  "canva": SiCanva,
  "slack": SiSlack,
  "jira": SiJira,
  "notion": SiNotion,
  "airtable": SiAirtable,
  "asana": SiAsana,
  "clickup": SiClickup,
  "trello": SiTrello,
  "monday.com": TbBrandMonday,
  "video production": TbBadge4K,
  "galaxy ecosystem": TbDeviceMobile,

  // Marketing & analytics
  "google analytics": SiGoogleanalytics,
  "ga4": SiGoogleanalytics,
  "google ads": SiGoogleads,
  "google search console": SiGooglesearchconsole,
  "google sheets": SiGooglesheets,
  "hubspot": SiHubspot,
  "salesforce": SiSalesforce,
  "mailchimp": SiMailchimp,
  "sendgrid": SiSendgrid,
  "semrush": SiSemrush,
  "tableau": SiTableau,
  "looker": SiLooker,
  "intercom": SiIntercom,
  "zendesk": SiZendesk,
  "zapier": SiZapier,

  // Skills — marketing & strategy
  "marketing leadership": HiOutlineMegaphone,
  "brand strategy": HiOutlineLightBulb,
  "growth marketing": HiOutlineArrowTrendingUp,
  "demand generation": HiOutlineRocketLaunch,
  "gtm planning": HiOutlineMapPin,
  "revenue and p&l ownership": HiOutlineChartBar,
  "team management": HiOutlineUserGroup,
  "operations": HiOutlineCog6Tooth,
  "marketing automation": HiOutlineBolt,
  "data and analytics": HiOutlineChartPie,
  "stakeholder alignment": HiOutlineHandRaised,
  "product collaboration": HiOutlineCubeTransparent,
  "digital marketing": HiOutlineCursorArrowRays,
  "performance marketing": HiOutlinePresentationChartLine,
  "crm": HiOutlineEnvelope,
  "martech": HiOutlineWrenchScrewdriver,
  "go-to-market strategy": HiOutlineRocketLaunch,

  // Dev skills
  "devops": HiOutlineServerStack,
  "full-stack development": HiOutlineCodeBracket,
  "full-stack": HiOutlineCodeBracket,
  "fullstack": HiOutlineCodeBracket,
  "next.js + tailwindcss": SiNextdotjs,
  "cli": HiOutlineCommandLine,
  "bash": HiOutlineCommandLine,
};

export function getTechIcon(name: string): IconType | null {
  return iconMap[name.toLowerCase()] || null;
}
